apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gproduct-microservice-deployment
  template:
    metadata:
      labels:
        app: product-microservice-deployment
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always