apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: github-actions-gke-product-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: github-actions-gke-product
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80