apiVersion: v1
kind: Service
metadata:
  name: product-microservice-deployment
spec:
  selector:
    app: gproduct-microservice-deployment
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8081