database: mysql

spring:
  cloud:
    gcp:
      credentials:
        location: service-account-key.json
      sql:
        database-name: productdb
        instance-connection-name: golden-ego-381501:us-east5:elg5164-product-db
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    hikari:
      maximum-pool-size: 25
      minimum-idle: 1
      password: admin1234
server:
  port: 8081

management:
  enable:
    process:
      cpu:
        usage: true

  endpoints:
    web:
      exposure:
        include: '*'

prometheus:
  metrics:
    export:
      enabled: true
